version: "3.9"
services:

  postgres:
    container_name: postgres
    image: "postgres:14.1-alpine"
    #restart: "always"
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=726354Valami01
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_init:/docker-entrypoint-initdb.d